//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Inputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inputs"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""c169d9f0-7602-49f6-af7a-70374ce837af"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""ebe69b4b-40be-4e9d-9d5e-eb4c13b0324b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9184e4e4-d5cc-41c2-b70d-0f2689e983da"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5c3edde7-96c3-4a1c-b073-c833b154402c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCam"",
                    ""type"": ""Button"",
                    ""id"": ""ecf84e6c-4c5c-467e-9d78-00ee0da2a0fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""d5ed419b-f903-4eeb-8d36-d7add493e3e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""bb673044-db98-4624-8c07-6ef0f8e48920"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleMouse"",
                    ""type"": ""Button"",
                    ""id"": ""7eb72444-4125-4b2f-8c59-bfabc9721deb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scroll"",
                    ""type"": ""Value"",
                    ""id"": ""6c6a9fff-cacf-4a77-8ef8-355e7be9f2d5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RandomForce"",
                    ""type"": ""Button"",
                    ""id"": ""6d03e39e-27aa-4e6c-949a-f3729f069418"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch1"",
                    ""type"": ""Button"",
                    ""id"": ""4319db70-2570-4c57-9755-19b2828d2bd8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch2"",
                    ""type"": ""Button"",
                    ""id"": ""4cdccc36-1e3a-4532-a226-ff9c9f697738"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch3"",
                    ""type"": ""Button"",
                    ""id"": ""037234ec-7c5b-465a-a6a8-d711f4d5b899"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch4"",
                    ""type"": ""Button"",
                    ""id"": ""47f90af1-c276-4066-9319-a821d5af8ba9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch5"",
                    ""type"": ""Button"",
                    ""id"": ""7cf1dd4f-beb1-44cf-8991-797982aa89a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch6"",
                    ""type"": ""Button"",
                    ""id"": ""e4c147cb-0775-4c53-a86a-74c81de3d081"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch7"",
                    ""type"": ""Button"",
                    ""id"": ""f12782fe-e58f-459e-8ba1-112b0f52e88c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch8"",
                    ""type"": ""Button"",
                    ""id"": ""f516396e-aee5-4cf1-b11a-5cac0d894d99"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch9"",
                    ""type"": ""Button"",
                    ""id"": ""1e75e73e-2764-44a8-84e0-4d4ddb74c0bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch0"",
                    ""type"": ""Button"",
                    ""id"": ""5006d2ab-2fbe-4855-a121-9fe0488803c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DisplayInfo"",
                    ""type"": ""Button"",
                    ""id"": ""f55415f4-5318-4ed4-9917-fe3e8b05133c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""0ab10763-4b08-4152-8010-7683b7a85649"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenInventory"",
                    ""type"": ""Button"",
                    ""id"": ""7fe385e7-45f0-4428-9432-83bff5fdfd4b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8e9de671-beb6-4039-9726-61ce7ebe4967"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f2ad879d-e984-4714-90c0-986cb92a433c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8628bbb1-6f18-4184-82e9-0510aacb03c9"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WSAD"",
                    ""id"": ""20a0f830-86fb-4614-9db9-8463d2438d7a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2b4d6084-ca89-4379-8390-4b02d6fc592d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f515ec59-5591-43e8-abbf-94bd6f7bf1a7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d3cc6739-15f4-477d-ab08-ed1a6bc69cd4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ac7a8af0-7332-4668-838b-34f14667c7c8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""46ad3df8-bdae-471e-9108-ce69edfe815f"",
                    ""path"": ""<Keyboard>/f5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf0180e1-4858-4653-bab1-611aad298653"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7f4c81f-2e2b-4e53-ad92-4440edba6b27"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9514423-cde6-40c4-8ba0-9f030887825f"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MiddleMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b08e3ce-b627-448f-ba86-f95effc714fe"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b88cc490-d5d7-4804-8dcd-05233d9c9e93"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RandomForce"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0e3dcba-8d57-4379-8b67-e5d3e7169736"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8583ea99-4b1d-491f-affd-687064ac0f69"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43d01069-c63b-4680-8067-27b27f0db6e6"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e783a038-39bb-4506-9809-e1d5eb0f0f7f"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f0bb14a-55a5-4956-b9c6-6fddc31405ae"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f25a0cb-c3a2-4337-bd92-1684c30a8747"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7cc213db-b45a-42e0-aee1-34ffd2ecd956"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ffe3cfb-0192-4a50-b0c4-d5599f89cb79"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1efb5d97-e6c3-4c59-9dcd-07742ae94837"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbaafb3f-462e-45ea-a20e-516950a1c257"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99eab189-7cd8-4a61-a5e0-a86f4ee68eea"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DisplayInfo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""574e0b1c-5ed6-4538-a75c-d802786a7d58"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26de7f2d-189d-40b0-89e1-383bbfcb5cc7"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""baa8f597-5cf5-465d-9848-46f1db9ca0ab"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Mouse = m_Player.FindAction("Mouse", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_SwitchCam = m_Player.FindAction("SwitchCam", throwIfNotFound: true);
        m_Player_LeftClick = m_Player.FindAction("LeftClick", throwIfNotFound: true);
        m_Player_RightClick = m_Player.FindAction("RightClick", throwIfNotFound: true);
        m_Player_MiddleMouse = m_Player.FindAction("MiddleMouse", throwIfNotFound: true);
        m_Player_Scroll = m_Player.FindAction("Scroll", throwIfNotFound: true);
        m_Player_RandomForce = m_Player.FindAction("RandomForce", throwIfNotFound: true);
        m_Player_Switch1 = m_Player.FindAction("Switch1", throwIfNotFound: true);
        m_Player_Switch2 = m_Player.FindAction("Switch2", throwIfNotFound: true);
        m_Player_Switch3 = m_Player.FindAction("Switch3", throwIfNotFound: true);
        m_Player_Switch4 = m_Player.FindAction("Switch4", throwIfNotFound: true);
        m_Player_Switch5 = m_Player.FindAction("Switch5", throwIfNotFound: true);
        m_Player_Switch6 = m_Player.FindAction("Switch6", throwIfNotFound: true);
        m_Player_Switch7 = m_Player.FindAction("Switch7", throwIfNotFound: true);
        m_Player_Switch8 = m_Player.FindAction("Switch8", throwIfNotFound: true);
        m_Player_Switch9 = m_Player.FindAction("Switch9", throwIfNotFound: true);
        m_Player_Switch0 = m_Player.FindAction("Switch0", throwIfNotFound: true);
        m_Player_DisplayInfo = m_Player.FindAction("DisplayInfo", throwIfNotFound: true);
        m_Player_Escape = m_Player.FindAction("Escape", throwIfNotFound: true);
        m_Player_OpenInventory = m_Player.FindAction("OpenInventory", throwIfNotFound: true);
        m_Player_MousePosition = m_Player.FindAction("MousePosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Mouse;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_SwitchCam;
    private readonly InputAction m_Player_LeftClick;
    private readonly InputAction m_Player_RightClick;
    private readonly InputAction m_Player_MiddleMouse;
    private readonly InputAction m_Player_Scroll;
    private readonly InputAction m_Player_RandomForce;
    private readonly InputAction m_Player_Switch1;
    private readonly InputAction m_Player_Switch2;
    private readonly InputAction m_Player_Switch3;
    private readonly InputAction m_Player_Switch4;
    private readonly InputAction m_Player_Switch5;
    private readonly InputAction m_Player_Switch6;
    private readonly InputAction m_Player_Switch7;
    private readonly InputAction m_Player_Switch8;
    private readonly InputAction m_Player_Switch9;
    private readonly InputAction m_Player_Switch0;
    private readonly InputAction m_Player_DisplayInfo;
    private readonly InputAction m_Player_Escape;
    private readonly InputAction m_Player_OpenInventory;
    private readonly InputAction m_Player_MousePosition;
    public struct PlayerActions
    {
        private @Inputs m_Wrapper;
        public PlayerActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Mouse => m_Wrapper.m_Player_Mouse;
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @SwitchCam => m_Wrapper.m_Player_SwitchCam;
        public InputAction @LeftClick => m_Wrapper.m_Player_LeftClick;
        public InputAction @RightClick => m_Wrapper.m_Player_RightClick;
        public InputAction @MiddleMouse => m_Wrapper.m_Player_MiddleMouse;
        public InputAction @Scroll => m_Wrapper.m_Player_Scroll;
        public InputAction @RandomForce => m_Wrapper.m_Player_RandomForce;
        public InputAction @Switch1 => m_Wrapper.m_Player_Switch1;
        public InputAction @Switch2 => m_Wrapper.m_Player_Switch2;
        public InputAction @Switch3 => m_Wrapper.m_Player_Switch3;
        public InputAction @Switch4 => m_Wrapper.m_Player_Switch4;
        public InputAction @Switch5 => m_Wrapper.m_Player_Switch5;
        public InputAction @Switch6 => m_Wrapper.m_Player_Switch6;
        public InputAction @Switch7 => m_Wrapper.m_Player_Switch7;
        public InputAction @Switch8 => m_Wrapper.m_Player_Switch8;
        public InputAction @Switch9 => m_Wrapper.m_Player_Switch9;
        public InputAction @Switch0 => m_Wrapper.m_Player_Switch0;
        public InputAction @DisplayInfo => m_Wrapper.m_Player_DisplayInfo;
        public InputAction @Escape => m_Wrapper.m_Player_Escape;
        public InputAction @OpenInventory => m_Wrapper.m_Player_OpenInventory;
        public InputAction @MousePosition => m_Wrapper.m_Player_MousePosition;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Mouse.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouse;
                @Mouse.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouse;
                @Mouse.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouse;
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @SwitchCam.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchCam;
                @SwitchCam.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchCam;
                @SwitchCam.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchCam;
                @LeftClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftClick;
                @LeftClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftClick;
                @LeftClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftClick;
                @RightClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightClick;
                @MiddleMouse.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMiddleMouse;
                @MiddleMouse.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMiddleMouse;
                @MiddleMouse.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMiddleMouse;
                @Scroll.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnScroll;
                @Scroll.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnScroll;
                @Scroll.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnScroll;
                @RandomForce.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRandomForce;
                @RandomForce.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRandomForce;
                @RandomForce.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRandomForce;
                @Switch1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch1;
                @Switch1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch1;
                @Switch1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch1;
                @Switch2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch2;
                @Switch2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch2;
                @Switch2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch2;
                @Switch3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch3;
                @Switch3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch3;
                @Switch3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch3;
                @Switch4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch4;
                @Switch4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch4;
                @Switch4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch4;
                @Switch5.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch5;
                @Switch5.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch5;
                @Switch5.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch5;
                @Switch6.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch6;
                @Switch6.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch6;
                @Switch6.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch6;
                @Switch7.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch7;
                @Switch7.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch7;
                @Switch7.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch7;
                @Switch8.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch8;
                @Switch8.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch8;
                @Switch8.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch8;
                @Switch9.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch9;
                @Switch9.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch9;
                @Switch9.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch9;
                @Switch0.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch0;
                @Switch0.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch0;
                @Switch0.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitch0;
                @DisplayInfo.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDisplayInfo;
                @DisplayInfo.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDisplayInfo;
                @DisplayInfo.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDisplayInfo;
                @Escape.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEscape;
                @OpenInventory.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOpenInventory;
                @OpenInventory.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOpenInventory;
                @OpenInventory.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOpenInventory;
                @MousePosition.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMousePosition;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Mouse.started += instance.OnMouse;
                @Mouse.performed += instance.OnMouse;
                @Mouse.canceled += instance.OnMouse;
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @SwitchCam.started += instance.OnSwitchCam;
                @SwitchCam.performed += instance.OnSwitchCam;
                @SwitchCam.canceled += instance.OnSwitchCam;
                @LeftClick.started += instance.OnLeftClick;
                @LeftClick.performed += instance.OnLeftClick;
                @LeftClick.canceled += instance.OnLeftClick;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
                @MiddleMouse.started += instance.OnMiddleMouse;
                @MiddleMouse.performed += instance.OnMiddleMouse;
                @MiddleMouse.canceled += instance.OnMiddleMouse;
                @Scroll.started += instance.OnScroll;
                @Scroll.performed += instance.OnScroll;
                @Scroll.canceled += instance.OnScroll;
                @RandomForce.started += instance.OnRandomForce;
                @RandomForce.performed += instance.OnRandomForce;
                @RandomForce.canceled += instance.OnRandomForce;
                @Switch1.started += instance.OnSwitch1;
                @Switch1.performed += instance.OnSwitch1;
                @Switch1.canceled += instance.OnSwitch1;
                @Switch2.started += instance.OnSwitch2;
                @Switch2.performed += instance.OnSwitch2;
                @Switch2.canceled += instance.OnSwitch2;
                @Switch3.started += instance.OnSwitch3;
                @Switch3.performed += instance.OnSwitch3;
                @Switch3.canceled += instance.OnSwitch3;
                @Switch4.started += instance.OnSwitch4;
                @Switch4.performed += instance.OnSwitch4;
                @Switch4.canceled += instance.OnSwitch4;
                @Switch5.started += instance.OnSwitch5;
                @Switch5.performed += instance.OnSwitch5;
                @Switch5.canceled += instance.OnSwitch5;
                @Switch6.started += instance.OnSwitch6;
                @Switch6.performed += instance.OnSwitch6;
                @Switch6.canceled += instance.OnSwitch6;
                @Switch7.started += instance.OnSwitch7;
                @Switch7.performed += instance.OnSwitch7;
                @Switch7.canceled += instance.OnSwitch7;
                @Switch8.started += instance.OnSwitch8;
                @Switch8.performed += instance.OnSwitch8;
                @Switch8.canceled += instance.OnSwitch8;
                @Switch9.started += instance.OnSwitch9;
                @Switch9.performed += instance.OnSwitch9;
                @Switch9.canceled += instance.OnSwitch9;
                @Switch0.started += instance.OnSwitch0;
                @Switch0.performed += instance.OnSwitch0;
                @Switch0.canceled += instance.OnSwitch0;
                @DisplayInfo.started += instance.OnDisplayInfo;
                @DisplayInfo.performed += instance.OnDisplayInfo;
                @DisplayInfo.canceled += instance.OnDisplayInfo;
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
                @OpenInventory.started += instance.OnOpenInventory;
                @OpenInventory.performed += instance.OnOpenInventory;
                @OpenInventory.canceled += instance.OnOpenInventory;
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnMouse(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnSwitchCam(InputAction.CallbackContext context);
        void OnLeftClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnMiddleMouse(InputAction.CallbackContext context);
        void OnScroll(InputAction.CallbackContext context);
        void OnRandomForce(InputAction.CallbackContext context);
        void OnSwitch1(InputAction.CallbackContext context);
        void OnSwitch2(InputAction.CallbackContext context);
        void OnSwitch3(InputAction.CallbackContext context);
        void OnSwitch4(InputAction.CallbackContext context);
        void OnSwitch5(InputAction.CallbackContext context);
        void OnSwitch6(InputAction.CallbackContext context);
        void OnSwitch7(InputAction.CallbackContext context);
        void OnSwitch8(InputAction.CallbackContext context);
        void OnSwitch9(InputAction.CallbackContext context);
        void OnSwitch0(InputAction.CallbackContext context);
        void OnDisplayInfo(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
        void OnOpenInventory(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
    }
}
